# -*- coding: utf-8 -*-
"""average.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO_QHcd_MWdBjsXp1sdY_8MJ3sfa7ERo
"""

#Q1="""1.Calculation of Test Average: Write a python program to find the best of two test average marks out of three test’s mark
print(Q1)
# Accept marks from user
m1 = int(input("Enter marks for Test 1: "))
m2 = int(input("Enter marks for Test 2: "))
m3 = int(input("Enter marks for Test 3: "))
# Find the minimum (lowest) mark to exclude
minimum = min(m1, m2, m3)
# Sum the best two marks
sum_best_two = m1 + m2 + m3 - minimum
# Calculate average of best two
average_best_two = sum_best_two / 2
print("Average of best two test marks is:", average_best_two)