# -*- coding: utf-8 -*-
"""binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCH-CCURnPRPjnFXOxxW4mLb3T7fvoHx
"""

#Q4="""Binary to Decimal & Octal to Hexadecimal Conversion: Develop a python program to convert binary to decimal, octal to hexa
print(Q4)
def binary_to_decimal(binary_str):
  # Convert binary string to decimal integer
  try:
    return int(binary_str, 2)
  except ValueError:
    return "Invalid binary input. Please enter a valid binary number (0s and 1s)."

def octal_to_hexadecimal(octal_str):
  # Convert octal string to decimal integer, then to hexadecimal (uppercase, without '0x')
  try:
    return hex(int(octal_str, 8))[2:].upper()
  except ValueError:
    return "Invalid octal input. Please enter a valid octal number (0-7)."

# Input from user
binary = input("Enter a binary number: ")
octal = input("Enter an octal number: ")

# Function calls and output
print("Decimal value of binary:", binary_to_decimal(binary))
print("Hexadecimal value of octal:", octal_to_hexadecimal(octal))
print("---------------------------------------------1")