# -*- coding: utf-8 -*-
"""prg12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBq16h0AhrEL8_ZQMPLVcnexPBhlZG8L
"""

#Q10= """Employee Details: Write a python program by creating a class called Employee to store
the details of Name, Employee_ID, Department and Salary, and implement a method to
update salary of employees belonging to a given department."""
print(Q10)
class Employee:
    def __init__(self, name, employee_id, department, salary):
        self.name = name
        self.employee_id = employee_id
        self.department = department
        self.salary = salary
    def update_salary(self, new_salary):
        self.salary = new_salary

def update_salary_by_department(employees, department, new_salary):
    for employee in employees:
        if employee.department == department:
            employee.update_salary(new_salary)

# Example usage
employees = [
    Employee("Ram", 101, "HR", 50000),
    Employee("Sitha", 102, "Finance", 60000),
    Employee("Hanuman", 103, "HR", 55000),
    Employee("Lakshman", 104, "IT", 70000),
]
print("Before salary update:")
for emp in employees:
    print(emp.name, emp.department, emp.salary)
update_salary_by_department(employees, "HR", 60000)
print("\nAfter salary update for HR department:")
for emp in employees:
    print(emp.name, emp.department, emp.salary)