# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xk-GUlNowmHxHxgfJ_aGh_b0udbjx7m7
"""

#Q3="""3. Fibonacci sequence: Defined as a function F as Fn = Fn-1 + Fn-2. Write a Python program which accepts a value for N (w
print(Q3)
def fibonacci_sequence(N):
  if N <= 0:
    print("Error: N must be greater than 0.")
    return

  fib_list = []
  a, b = 0, 1
  for _ in range(N):
    fib_list.append(a)
    a, b = b, a + b

  print("Fibonacci sequence up to", N, "terms:", fib_list)

try:
  N = int(input("Enter the number of terms (N > 0): "))
  fibonacci_sequence(N)
except ValueError:
  print("Error: Please enter a valid integer.")