# -*- coding: utf-8 -*-
"""frequency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDskrdNn09w66jb1LXpZYy9b6UHEyhin
"""

#Q3="""write a python program to check if a number is a palindrome and count the frequency of each digit
number = input("Enter a number: ")
if number == number[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")
for i in range(10):
    count = number.count(str(i))
    if count > 0:
        print(f"{i} appears {count} times")