# -*- coding: utf-8 -*-
"""import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXFKO32Vb6tUpnfRCsZdgS3V9IwSrjYg
"""

#Q13="""Spreadsheet Operations: Demonstrate python program to read the data from the

!pip install PyPDF2
from PyPDF2 import PdfReader, PdfWriter
from google.colab import files
# Upload PDF files
print("Please upload the first PDF file:")
uploaded1 = files.upload()
pdf1_path = list(uploaded1.keys())[0]
print("Please upload the second PDF file:")
uploaded2 = files.upload()
pdf2_path = list(uploaded2.keys())[0]
# Function to merge two PDFs
def merge_two_pdfs(pdf1_path, pdf2_path, output_path):
    pdf_writer = PdfWriter()
    pdf1_reader = PdfReader(pdf1_path)
    for page in pdf1_reader.pages:
        pdf_writer.add_page(page)
    pdf2_reader = PdfReader(pdf2_path)
    for page in pdf2_reader.pages:
        pdf_writer.add_page(page)
    with open(output_path, 'wb') as output_pdf:
        pdf_writer.write(output_pdf)
    print(f'Merged PDF saved as {output_path}')
# Call function and merge PDFs