# -*- coding: utf-8 -*-
"""inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqjRdTFlgoZ_x9iASyYPjfEpJn3iOCbS
"""

#Q9 ="""Inheritance: By using the concept of inheritance write a python program to find the area
of triangle, circle and rectangle."""
print(Q9)
import math
def area_of_triangle(base, height):
    return 0.5 * base * height
def area_of_circle(radius):
    return math.pi * radius ** 2
def area_of_rectangle(length, width):
    return length * width
# Example usage:
print("Area of triangle:", area_of_triangle(5, 10)) # base=5, height=10
print("Area of circle:", area_of_circle(7)) # radius=7
print("Area of rectangle:", area_of_rectangle(4, 8)) # length=4, width=8