# -*- coding: utf-8 -*-
"""insertion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8SxnMoIoQaxBp43ycjrfCyF2UCgzM5v
"""

#Q71="7.1. Write a python program to implement insertion sort using lists."
print(def insertion_sort(arr):
  for i in range(1, len(arr)):
    key = arr[i]
    j = i - 1
    while j >= 0 and arr[j] > key:
      arr[j + 1] = arr[j]
      j -= 1
    arr[j + 1] = key

# Example usage:
nums = [8, 7, 13, 1, -9, 4]
insertion_sort(nums)
print("Insertion sort result:", nums)