# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZ86XIaLlnB3lTjTVrVZvDIBOS2QRp47
"""

#Q72="7.2. Write a python program to implement merge sort using lists."
print(Q72)
def merge_sort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])
    return merge(left, right)

def merge(left, right):
    result = []
    i = j = 0
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1
    result.extend(left[i:])
    result.extend(right[j:])
    return result

# Example usage
lst = [5, 2, 9, 1, 5, 6]
print("Sorted Merge sort list:", merge_sort(lst))