# -*- coding: utf-8 -*-
"""operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcmWkOPU5bPyEqAB9wWYOxtkYkOqFTfM
"""

#Q8="""File Operations: Write a python program to accept a file name from the user and
perform the following operations
1. Display the first N line of the file
2. Find the frequency of occurrence of the word accepted from the user in the file"""
print(Q8)
# File Operations: Display first N lines and count word frequency
# File Operations: Display first N lines and count word frequency with file path input
file_path = input("Enter full file path: ")
try:
    N = int(input("Enter number of lines to display: "))
    search_word = input("Enter word to find frequency: ")
    line_count = 0
    word_count = 0
    with open(file_path, 'r', encoding='utf-8') as file:
        print(f"\nFirst {N} lines of the file:")
        for line in file:
            if line_count < N:
                print(line.rstrip())
            line_count += 1
            # Count word frequency for all lines
            word_count += sum(word == search_word for word in line.split())
    print(f"\nFrequency of '{search_word}' in the file: {word_count}")
except FileNotFoundError:
    print("File not found. Please check the file path and try again.")
except ValueError:
    print("Please enter a valid number for N.")
except Exception as e:
    print(f"An error occurred: {e}")