# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PX3aLIVv-d11mlRItluy1qsMuooZF04z
"""

#Q2="""1.write a python program to check whether a given string is a palindrome and display the frequency of each character in the string
input_str = input("Enter a string: ")
if input_str == input_str[::-1]:
  print("Palindrome")
else:
  print("Not Palindrome")
for ch in set(input_str):
  count = input_str.count(ch)
  print(f"'{ch}' appears {count} times")