# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCanEmEwqAmTrCfmbDvJAPYSTVzklcaC
"""

#Q6="Similarity: Write a Python program to find the string similarity between two given strings."
print(Q6)
from difflib import SequenceMatcher

def string_similarity(str1, str2):
    # Create a SequenceMatcher object
    matcher = SequenceMatcher(None, str1, str2)
    # Return similarity ratio
    return matcher.ratio()

# Example usage:
s1 = "Python Exercises"
s2 = "Python Exercise"
print("Similarity:", string_similarity(s1, s2))